### ISSUE TITLE
[Bug] "hydra/job_logging: disabled" disables all existing loggers

### ISSUE THREAD

**Issue by Vozf** [facebookresearch/hydra#1018]
When "hydra/job_logging": "disabled" all existing non hydra loggers are also disabled. This is unexpected behavior. When setting this flag I expect to disable only hydra logging features not disable all the loggers in program

**Comment by omry** [comment]
This is disabling logging and it is as intended.
you can create your own logging configuration and use that instead.
See the docs for reference.

**Comment by Vozf** [comment]
What is a configuration to disable all hydra logging and leave all the logging in my application unouched? And why isn't it described in the documentation?

**Comment by Vozf** [comment]
> Hydra is a framework for elegantly configuring complex applications
Interfering with all the logging with no way to disable it without digging the framework source cde doesn't seem like any of that

**Comment by omry** [comment]
You are describing a missing feature, we already discussed it in a different issue.
Open a new feature request. If this is urgent you can help implement it.

If in general you are not satisfied with the service you are getting just say and I will issue a complete refund.

**Comment by Vozf** [comment]
Thanks. That's a level of support I would expect from facebookresearch

**Comment by omry** [comment]
Yup. and this is the attitude I would expect from a random person on the Internet.

**Comment by omry** [comment]
Looking at the previous issue you opened (duplicate logging - where you didn't bother to provide a repro), I gave you the wrong advice.
setting the logging to disabled turns off all the loggers, not disabling the configuration of the loggers.
Sorry about that.

When I said "we discussed in the other issue", I meant [this](https://github.com/facebookresearch/hydra/issues/1005#issuecomment-697036570), which is not your issue. I confused your report with the other person's report. Sorry about that too.

Logging did not change much since the inception of Hydra. It's certainly not a high priority area and I agree that there are rough edges. The plan is to at least allow an easy way to disable the configuration (I opened #1021 to track this).

Hydra is using Python dictConfig standard API to configure the logging.
It takes a dictionary to applies it as configuration to the logging subsystem.
Specifically, the "disabled" configuration that you point you to is defined [here](https://github.com/facebookresearch/hydra/blob/master/hydra/conf/hydra/job_logging/disabled.yaml) and is designed to do exactly what you reported as a bug (disable all logging). It's primarily intended for unit tests where logging can get in the way.
You can create your own logging configs similar to those in Hydra to control the configuration Hydra is using to configure the Python logging, but I am not sure you can use it to completely disable the configuration. (some docs about [here](https://hydra.cc/docs/configure_hydra/logging)).

Orthogonal to all of this:
I do not work for you. I have long term plans and I prioritize accordingly.
If you do not like my priorities you can try to help with a pull request after a short chat to make sure you are attempting something that is in line with the project plans.

**Comment by Vozf** [comment]
For anyone wondering how to disable hydra interfering with the logs in a structured config. This is what works for me
```
cs = ConfigStore.instance()
cs.store(
    name="disable_hydra_logging",
    group="hydra/job_logging",
    node={"version": 1, "disable_existing_loggers": False, "root": {"handlers": []}},
)

@dataclass
class Config:
    defaults: List = field(
        default_factory=lambda: [
            {"hydra/job_logging": "disable_hydra_logging"},
        ]
    )


cs.store(name="config", node=Config)
```

**Comment by dalgu90** [comment]
For anyone looking for how to prevent hydra from disabling all existing loggers in a hydra config yaml. This is what works for me,
``` YAML
defaults:
  - ... (your usual defaults)
  - _self_

# your other configs

hydra:
  output_subdir: null
  run:
    dir: .
  job_logging:
    version: 1
    disable_existing_loggers: false
    root:
      handlers: []
```

**Comment by abdulfatir** [comment]
I believe it would be great to have an option preventing hydra from touch logging stuff. I would like to keep the loggers and handlers specified in the logger without having to define them in the yaml config. Also, options like verbosity appear to affect _all_ loggers. This is something I did not expect.
