### ISSUE TITLE
[Feature Request] Support using .yml file extension instead of .yaml

### ISSUE THREAD

**Issue by KamWithK** [facebookresearch/hydra#1050]
# 🚀 Feature Request

In a lot of projects, the `.yml` file extension is used instead of `.yaml` as it is slightly more concise and I've seen and used it more often.
Hence, would it be possible to either find and use both `.yml` and `.yaml` files or to have a simple parameter which switches between whether to look for `.yaml` or `.yml`?

## Motivation

In a lot of projects, the `.yml` file extension is used instead of `.yaml` as it is slightly more concise and I've seen and used it more often.
In my project, we have a large number of configuration files (not just for Hydra) and the `.yml` file extension has already been chosen.
Now that I'm implementing Hydra into our model creation and training code, it is frusturating to have to see that half my configuration uses `.yml` and the other half `.yaml`.
The issue was previouslly raised and closed [here](https://github.com/facebookresearch/hydra/issues/398) due to difficulty checking for two file types.
BUT, if instead of checking for both there was a parameter declairing which was used it might make it easier to deal with

**Comment by omry** [comment]
Thanks for your suggestion.
This is unfortunately more complicated than it seems:

1. This cannot be configured in the config files because how would that file be found?
2. Hydra itself, as well as Hydra plugins and installed frameworks may be accessing config files they installed, changing the extension will break all of them.

Overall I think the utility from this is very low and it's not worth the added complexity and implementation effort.
#408 is a similar feature request to support json files that I am keeping open (yaml is a superset of json so this is really about supporting another file extension).
The chances of it being implemented are low but I am not completely ruling it out yet.

Closing this one, feel free to continue discussing here.

**Comment by andrewnaguib** [comment]
Wouldn't supporting `.yml` along with `.yaml` files be a wider scope of interoperability. I am not motivating to use `yml` instead, but supporting it too. If you are convinced, I will be happy to implement it with some guidance tips.

**Comment by omry** [comment]
Read my reasons above and in #408 to only support `.yaml` for config file extension.
That decision is made.
