### ISSUE TITLE
[Feature Request] Set environment variables when using compose API

### ISSUE THREAD

**Issue by victorjoos** [facebookresearch/hydra#1181]
# 🚀 Feature Request

Adding the variables in hydra.job.env_set to the environment variables when using compose (for example in jupyter notebooks)

## Motivation

When I use the compose API in a jupyter notebook, I have to manually add environment variables that I already set with env_set, and it's a duplication for not much information.

## Pitch

**Describe the solution you'd like**

I would like to be able to set an `set_env=True` when using compose which would add all environment variables in the list.

**Describe alternatives you've considered**

For the moment I use the internal `env_override` function, but using a context manager in a notebook is not really practical.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

Yes

**Comment by victorjoos** [comment]
Rereading the source of `env_override`, I simply do `os.environ.update(cfg.hydra.job.env_set)` for now (but for this I need to add hydra in my config...)

**Comment by omry** [comment]
By design, the compose API does not have any side effects.
This is very intentional.
It also does not configure the Python logging, and it also does not create a working directory for you etc.

These, and other functionalities are available through @hydra.main() - which does not make a lot of sense for Notebooks.

I don't feel adding a flags to the compose API to enable these side effects is a good approach here.
