### ISSUE TITLE
[Feature Request] Make .hydra output location configuable

### ISSUE THREAD

**Issue by veritas9872** [facebookresearch/hydra#1390]
# 🚀 Feature Request

I would like to request a small change so that the output root for the hydra run can be set from within the Python code.

I would like to configure the output directory of the .hydra file from within my Python code.

This would make it possible to specify my Hydra outputs to be in the same location as my model checkpoints.

However, to the best of my knowledge, the output directory of the `.hydra` and `PROJECT_NAME.log` files cannot be specified from within the python code, though they may be specifiable from the command line.

**Comment by veritas9872** [comment]
From the [docs](https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/) I am led to believe that Hydra changes the current working directory to `hydra.run.dir` and then saves everything in the current working directory. I am not sure if this is the best idea. I would like to request a proper configuration method from within the file.

**Comment by omry** [comment]
Your request is actually not small at all and a bit confused in my opinion.
The title of your issue is about `.hydra`, but you can [configure it](https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory#disabling-output-subdir).

In the content of your issue you are asking to set the output directory from Python code.
I am not sure when exactly you want to do it because by the time your function is running the output directory is already created.

You further say that you want to configure Hydra output dir to match where you place your models.
Why not configure the output dir through Hydra configs and then store your models there?

**Comment by omry** [comment]
Closing, feel free to follow up and clarify.

**Comment by hwijeen** [comment]
One example situation where you would want to be able to configure the output directory WITHIN python process is when running the code on a cloud service. 

I am running a hydra-based python script on a cloud server, which basically is running a Docker container on a cloud server. The thing is that I need to save outputs on the specific directory that is mounted to my local machine (something like `/mnt/here`), in stead of `./outputs`. The specific path is only accessible within python (something like `from LIB import SPECIFICPATH`).

I am not sure how many people would be in a similar situation, but it would definitely be wonderful if configuring within python functionality is ADDED on top of everything that's possible at the moment. If it is too much of a burden, I would appreciate your advice on how to make it happened in a hacky way. I thought using OmegaConf's value interpolation would do the job, but it seems not possible  after looking at `run_job` function. Help me out!

**Comment by omry** [comment]
Your question is not clear. and I don't think clarifying one unclear question over an issue that was closed because it was unclear makes sense.
file a new one and we can discuss your use case.
