### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by andrewnaguib** [facebookresearch/hydra#1409]
# 🚀 Feature Request

Natively unpacking kwagrs configurations to the task function when decorated by `hydra.main` (i.e., not passing the configuration object)

## Motivation

1. More intuitive to write the signature of my function to expose the parameters it needs (even for IDE inspection intellisense). In the current situation, the function signature has to take a config file. 
2. Better code quality

## Pitch

**Describe the solution you'd like**
Modifying the following line:

https://github.com/facebookresearch/hydra/blob/4ba24129fff5ad274611ccd63a07532ff8d44585/hydra/core/utils.py#L128

to 

```Python
            ret.return_value = task_function(**task_cfg)
```

**Note**: not sure of the consequences. 

**Describe alternatives you've considered**

```Python
from omegaconf import DictConfig, OmegaConf
import hydra

def unpack(fn):
    def unpack_config(args):
        return fn(**args)
    return unpack_config


@hydra.main(config_name='config')
@unpack
def my_app(x, y) -> None:
    print(x + y)

if __name__ == "__main__":
    my_app()
```

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

Yes

**Comment by omry** [comment]
Hi @andrewnaguib.
While this is a nice idea, I think it makes more sense for Hydra to provide the config as a single object.
For example, interpolation would break if you do that because the root of the config will be gone.

To achieve higher code quality, look at Structured Configs (new in Hydra 1.0).
They will allow you to describe your configuration structure  using dataclasses. With duck typing your IDE will be able to assist you.
