### ISSUE TITLE
[Bug] Ray plugin ConfigStore schema need to be renamed

### ISSUE THREAD

**Issue by samuelstanton** [facebookresearch/hydra#1471]
# 🐛 Bug
## Description
The Ray plugin (and possibly the other plugins as well) have not been fully migrated to Hydra 1.1. In particular, executing a command like `python my_app.py -m hydra/launcher=ray_aws` with a custom `ray_aws.yaml` config (as described in the plugin documentation) raises a deprecation warning. The fix may be as simple as just changing the schema names [here](https://github.com/facebookresearch/hydra/blob/master/plugins/hydra_ray_launcher/hydra_plugins/hydra_ray_launcher/_config.py#L257) as suggested in the Hydra 1.0 --> 1.1 migration docs. It's not a critical issue, but it will need to be resolved before Hydra 1.2 is released.

## Checklist
- [ x] I checked on the latest version of Hydra
- [ x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

I've created a minimal example here. 

https://github.com/samuelstanton/hydra-ray-demo

** Stack trace/error message **
```
UserWarning: 
'hydra/launcher/ray_aws' is validated against ConfigStore schema with the same name.
This behavior is deprecated in Hydra 1.1 and will be removed in Hydra 1.2.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/automatic_schema_matching for migration instructions.
```

## Expected Behavior
The example should run without warnings.

## System information
- **Hydra Version** :  1.1.0dev5
- **Python version** : 3.8.8
- **Virtual environment type and version** : conda 4.9.2
- **Operating system** : macOS Catalina, 10.15.7

**Comment by omry** [comment]
Hi @samuelstanton, thanks for filing.
We should definitely do something about it.
I see two approaches:

1. rename the base config to something like base_ray_aws,
2. Direct the users to create a config with a different name for their customized version (and update the examples accordingly).

There are pros and cons to each approach. Since most plugins base configs provides complete defaults, I am actually leaning toward 2 (otherwise running without a custom config, which is what most people will try first) will be weirder.
