### ISSUE TITLE
[Feature Request] Support Default List Overides in Subtree of Interpolated Config Group

### ISSUE THREAD

**Issue by Queuecumber** [facebookresearch/hydra#1561]
# 🚀 Feature Request

I have my configs set up such that the user can select a model on the command line and if a config with the same name exists in config group "overrides", it is automatically loaded: 

```
defaults:
  - experiment
  - model: ???
  - optional overrides: ${model}
 ```

currently, if a user tries to override something with a defaults list (for example, the `model` config has in its default list setting for the `data` config group), it errors out as expected with:

```
Default List Overrides are not allowed in the subtree
of an in interpolated config group (override data=color_patch).
```

I think this should eventually be a supported scenario

## Motivation

It's a fairly critical feature of this functionality im describing to be able to override config groups, and it makes the command line a lot more concise for the user, although it is easy enough to work around:

```
python -m mm.run.train model=my_model
```

automatically picking up the user's custom settings vs

```
python -m mm.run.train model=my_model overrides=my_model
```

## Pitch

**Describe the solution you'd like**
I think this should eventually be supported but I have no idea how you'd go about it. My guess is that this isn't supported because interpolations happen late in the process and defaults are potentially all worked out already.

**Describe alternatives you've considered**
Just using the workaround

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

Yes but I bet its complicated

**Comment by omry** [comment]
There are subtle details about the evaluation order that means supporting will open up a nasty Pandora's box.
Interpolation are evaluated at the end, once all the config groups are known. they cannot change them (and will never be able to for the sake of the sanity of future generations).

Instead of having a general purpose "overrides" config group, why add another model to the models config group, with a defaults list that will cause it to override the relevant model?
```
model/
  some_model.yaml
  some_model_ver2.yaml
```

model/some_model_ver2.yaml:
```yaml
defaults:
 - some_model

ver: 2
```

**Comment by Queuecumber** [comment]
The suggestion is a potential workaround but the easiest thing for the user is to dump their overrides into that per-model override config and run with that, it's more for one-off kind of quick experiments like changing out a dataset (in this example) or overriding the number of training epochs etc. Stuff you wouldnt really want an entire specialization of the model config for. 

The way I used to support this was the way I mentioned as a workaround:

```
python -m mm.run.train model=my_model overrides=my_model
```

but I thought it would be cool if the user can just have an appropriately named config and I could automatically pick that up since I know the model name anyway.

Another workaround is to simply hard code the model name for each model which also works fine, just a little bit more to remember when I write the model configs.

As far as actually supporting this, I opened this issue more as a thought for the future, the workaround is suitable for the foreseeable future but I do think its something that should eventually be worked out because as someone who only uses hydra, I would see the following two configs:

```
- optional overrides: ${model}
```

and 

```
- optional overrides: my_model
```

and expect them to work the same way (assuming `${model}` evaluates to "my_model") I wouldnt be expecting a crash, it's only because I know some things about hydra that I understand why this is a tricky situation. So maybe we can wishlist this?

**Comment by omry** [comment]
Defaults List interpolation predated the recursive defaults list support and in most cases is not needed at all now that it exists.
After spending 3 months on the new defaults list, I have no interest in investing more into that area any time soon.

> I thought it would be cool if the user can just have an appropriately named config and I could automatically pick that up since I know the model name anyway.

I would be cool. but that's not enough.
The Defaults List in 1.1 is - by far - the most complex piece of code in Hydra. the feature you are requesting will mean redesigning it ,and to be honest I don't even know if it's possible at all.

You are welcome to spend a few months trying to come up with a consistent design that meets the existing requirements and also what you are asking for. If you are successful I will consider integrating it.

Some food for thought: What happens if:
```yaml
defaults:
  - a_b: ${a}_${b} # a1_b1
  - a: a1
  - b: b1
```

and to make it interesting:
b/b1:
```yaml
defaults:
 override /a: a2
```

a/a2:
```yaml
defaults:
 override /b: b2
```

**Comment by Queuecumber** [comment]
> and in most cases is not needed at all now that it exists

That's interesting and there's a legitimate case to be made to deprecate the entire functionality, my case can definitely be resolved with only recursive defaults although it's slightly more verbose. The corner cases that come up certainly illustrate some of the cons of supporting it

**Comment by omry** [comment]
I considered dropping it while working on the new defaults list and decided against it. I might re-evaluate in the future.

I am closing this for now.
