### ISSUE TITLE
[Feature Request] Bool flags/optional parameters in shell app

### ISSUE THREAD

**Issue by SolomidHero** [facebookresearch/hydra#1575]
# 🚀 Feature Request

Is there any elegant way to define some bool flags for application. Example of solution for now:
**`config.yaml`**
```yaml
verbose: False # some flag for app.py
```

On launch:
```bash
$ python3 app.py verbose=True
```

## Motivation

Seems `=True` part is not cool

## Pitch

Any of these are visually better:
```bash
$ python3 app.py verbose
$ python3 app.py +verbose
```

which start hydra main with `verbose=True` parameter changed in config (only if it was defined in `config.yaml` as boolean otherwise error)

**Comment by omry** [comment]
The Hydra overrides grammar is already very complex and supporting this will limit the design space of how it can evolve.
I don't think this particular use case justifies special handling in the grammar.

I will keep this open for 6 months or so to see if it generates enough interest to consider it, but tat this time I am not planning to add support for it.

**Comment by KinWaiCheuk** [comment]
In machine learning experiments, we need to toggle certain features of our model on and off during different experiments. So boolean support will be very useful to us.

For example, we might want to fineturn/train specific layers of our model, then in our config file, we have something like this

```yaml
layer1_freeze: True
layer2_freeze: False
layer3_freeze: True
layer4_freeze: False

``` 

We might also want to try different combinations of the trainable layers, so that we can do the following command to try all the 16 combinations
`python train.py -m layer1_freeze=True,False layer2_freeze=True,Falses, layer3_freeze,=True,False layer4_freeze=True,False`

**Comment by Jasha10** [comment]
@KinWaiCheuk boolean values are already supported by Hydra. Your example above should work as-is.

The original post from this feature request was asking for a special grammar so that `python train.py layer1_freeze=True` is equivalent to `python train.py layer1_freeze`

**Comment by KinWaiCheuk** [comment]
@Jasha10 Thanks for the quick reply! After some more investigations, I realized that the problem in my case is due to the conflicts between the folder name and the yaml entry name.
For example, I have the file structure like this

```
├── train.py
└── config
       ├── config.yaml
       └── variable
             └── ...
```

And inside my `config.yaml`, I have one boolean variable conflicting with the folder with the same name  
 ```yaml 
layer1_freeze: True
layer2_freeze: False
variable: True
```

When I do `python train.py variable=False`, I get the following error.

> ValueError: Config group override must be a string or a list. Got bool

I am not using any `defaults_list`. Is it possible to make hydra stop thinking that the `variable` inside the config.yaml is not referring to the folder `variable` without changing the file structure or renaming the folder?

**Comment by Jasha10** [comment]
No, I'm sorry to say that you'll have to resolve the name conflict.
Even if you're not using a defaults list, the presence of the folder `variable` causes Hydra to interpret command-line overrides involving the name "variable" as being related to that folder.
