### ISSUE TITLE
Question - Defining a tuple as a parameter in a config file

### ISSUE THREAD

**Issue by dianemarquette** [facebookresearch/hydra#1642]
Hi! 

I'm using Hydra with PyTorch Lightning to configure my model. One of the hyperparameters of my data module is a variable that corresponds to a tuple of 3 floats. 

In the datamodule.yaml config file, I wrote:
```
_target_: src.datamodules.keri_datamodule.KeriDataModule
pix_dim: (0.5, 0.5, 0.781)
```

However, I get the following error:
`ValueError: Error instantiating 'src.datamodules.keri_datamodule.KeriDataModule': could not convert string to float: '(0.5, 0.5, 0.781)'`

What syntax should I use to explain to Hydra that it's a tuple / sequence and not a string or a list to sweep through? 

Thanks for your help :)

**Comment by Jasha10** [comment]
Currently tuples do not have full support (see https://github.com/omry/omegaconf/issues/392).
Is it possible to use a list, i.e. `pix_dim: [0.5, 0.5, 0.781]`?

**Comment by dianemarquette** [comment]
Hi @Jasha10 

Thanks for your answer. If I use a list, won't it consider the list values as values to sweep through?

**Comment by Jasha10** [comment]
Nope, give it a try :)
Sweeping is usually achieved at the command line using Hydra's [Multi-run](https://hydra.cc/docs/tutorials/basic/running_your_app/multi-run) syntax.

**Comment by dianemarquette** [comment]
OK, thanks for the clarification !

**Comment by aksg87** [comment]
@Jasha10 

So the workaround is to define a tuple as a list? Will this cause an error when trying to instantiate objects that expect a tuple or will duck typing solve things?

**Comment by Jasha10** [comment]
Hi @aksg87

> So the workaround is to define a tuple as a list?

The workaround is to use lists instead of tuples.

> Will this cause an error when trying to instantiate objects that expect a tuple or will duck typing solve things?

If you are instantiating `MyClass`, a list will be passed to `MyClass.__init__`. If `MyClass` can handle a list as input, there will be no error. If `MyClass` strictly requires a tuple, then this is a problem, and the workaround fails.

There is an open issue (https://github.com/omry/omegaconf/issues/392) to improve support for tuples on the OmegaConf side.

For now, here is one idea for handling a class that strictly requires a tuple as input (i.e. that cannot handle lists): write a thin wrapper class or a factory function, and use instantiate on that wrapper/factory instead. The wrapper/factory would translate the lists into tuples before instantiating the actual class.

**Comment by aksg87** [comment]
Thank you @Jasha10 -- The idea of using a wrapper/factory is great!

I had another related question that came up. Is there a way to pass a `dict` as an input during instantiation?

**Comment by Jasha10** [comment]
Yes, this is possible using `_convert_="all"`:
Given a yaml file that looks like this:
```yaml
my_class:
  _target_: my_app.MyClass
  pix_dim: [0.5, 0.5, 0.781]
  dict_arg:
    a: 123
    b:
      c: 456
```
You can instantiate this in your python file using `instantiate(cfg.my_app, _convert_="all")`, which will call `MyClass.__init__` with named arguments `pix_dim` and `dict_arg`.
```python
# equivalent to the following:
MyClass(pix_dim=[0.5, 0.5, 0.781], dict_arg={'a': 123, 'b': {'c': 456}})
```
The `_convert_="all"` keyword will ensure that `dict_arg` is passed to `MyClass.__init__` as a `dict` instead of as an `omegaconf.DictConfig` instance. It would also be possible to use the `_convert_` flag inside your yaml file:
```yaml
my_class:
  _target_: my_app.MyClass
  _convert_: all
  pix_dim: [0.5, 0.5, 0.781]
  dict_arg: {"a": 123, "b": {"c": 456}}
```
Please refer to the documentation on [instantiating objects](https://hydra.cc/docs/next/advanced/instantiate_objects/overview) for additional information.

**Comment by aksg87** [comment]
Thank you @Jasha10  🙂    Really helpful examples!

**Comment by janakact** [comment]
Maybe I am too late here, but hope this will help someone. 
You can directly specify the tuple using the standard YAML syntax for sequences, similar to a list but with an explicit conversion to a tuple.
```yaml
my_class:
  pix_dim: !!python/tuple [0.5, 0.5, 0.781]
```

**Comment by janakact** [comment]
Maybe this is unnecessary, but you can use a custom loader like below.  Then use `pix_dim: !tuple [0.5, 0.5, 0.781]`
```
import yaml
from omegaconf import OmegaConf

# Define a custom resolver for the !tuple tag
def tuple_constructor(loader, node):
    return tuple(loader.construct_sequence(node))

yaml.SafeLoader.add_constructor('!tuple', tuple_constructor)

# Load the configuration
config = OmegaConf.load('config.yaml')
print(config)
```

**Comment by sofeikov** [comment]
For anyone stumbling upon it, you can do the following:

```python
from omegaconf import OmegaConf

OmegaConf.register_new_resolver("as_tuple", lambda *args: tuple(args))
```

and then you config:
```
will_be_a_tuple: ${as_tuple:1,2,3}
```
