### ISSUE TITLE
[Bug] tilde ~ in override value will not work

### ISSUE THREAD

**Issue by roytseng-tw** [facebookresearch/hydra#1647]
# 🐛 Bug
## Description
tilde (~) at the beginning of the value results in `hydra.errors.OverrideParseException`

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
```
python main.py hydra.run.dir=~/outputs
```

** Stack trace/error message **
```
LexerNoViableAltException: hydra.run.dir=~/outputs
                                         ^
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

## Expected Behavior
work without error.

## System information
- **Hydra Version** :  1.0.6
- **Python version** :  3.6
- **Virtual environment type and version** :  pyenv 1.2.21
- **Operating system** :  linux ubuntu 16.04.3 LTS

## Additional context
None.

**Comment by Jasha10** [comment]
Hi @roytseng-tw,

Here is a workaround for your operating system: `python main.py hydra.run.dir=$HOME/outputs`.

Note that hydra gives special meaning to the `~` character; it is used for [removing a value](https://hydra.cc/docs/advanced/override_grammar/basic/#modifying-the-config-object) from your config object. You can find an example of usage [here](https://hydra.cc/docs/tutorials/basic/your_first_app/defaults#overriding-a-config-group-default).

**Comment by omry** [comment]
If you are expecting hydra.run.dir=~/outputs to expand to your home directory, this is a function of the shell.
You can try to echo it and see if your shell does it or not:
```
$ echo hydra.run.dir=~/outputs
hydra.run.dir=~/outputs
~ $ echo ~/outputs
/Users/omry/outputs
```
As you can see, my shell (bash) is not expanding ~ in the middle of a string.
This has nothing to do with Hydra.

The reason you are getting an error from Hydra is that ~ is a special character for Hydra as well and it can't appear in an unquoted string.
Since both Hydra and your shell will intercept quotes, you need to quote twice:
```
$ python my_app.py 'hydra.run.dir="~/outputs"'
```
However, because ~ is not expanded by the shell the output directory created will actually contain the `~` character.

**Comment by dave-epstein** [comment]
I think this is a related issue: I can't use the character λ without getting the LexerNoViableAltException, for example:
```
python script.py config.λ.some_value=0
```

Tried wrapping in single quotes too to no avail. Is there any workaround to this?

**Comment by omry** [comment]
Hydra command line overrides only support ascii characters.

**Comment by dave-epstein** [comment]
Alright. I used value interpolation as a cumbersome workaround.
