### ISSUE TITLE
[Bug] Accessing resolved field re-runs resolver

### ISSUE THREAD

**Issue by nils-werner** [facebookresearch/hydra#2037]
# 🐛 Bug
## Description

Whenever I am using a resolver, that resolver gets run. That is of course expected behaviour:

```
hello: ${test:1}   # runs resolver `test`
```

However when I access the resolved field `${hello}`, that resolver will run again. To me that is unexpected behaviour.

```
hello: ${test:1}   # runs resolver `test`
hello2: ${hello}   # runs resolver `test` again!
```

I would expect that the resolver is not run again, and instead just that already computed value is re-used.

I of course can use `OmegaConf.register_new_resolver(..., use_cache=true)`, but I would still expect it to not be re-run when accessing an intermediate field.

Or am I just misunderstanding a deliberate design choice?

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

```python
# test.py
import hydra
from omegaconf import OmegaConf

def test(x):
    print(f"running resolver 'test:{x}'")
    return x

OmegaConf.register_new_resolver("test", test)


@hydra.main(config_path="./", config_name="test.yaml")
def main(config):
    print(OmegaConf.to_yaml(config, resolve=True))


if __name__ == "__main__":
    main()
```

```yaml
# test.yaml
hello: ${test:1}
hello2: ${test:2}
hello3: ${hello2}
```

** Stack trace/error message **

```
running resolver 'test:1'
running resolver 'test:2'
running resolver 'test:2'
hello: 1
hello2: 2
hello3: 2
```

## Expected Behavior

The resolver should only run once

## System information
- **Hydra Version** :  1.1.1
- **Python version** : 3.9.9
- **Virtual environment type and version** : `python -m venv`
- **Operating system** : macOS Monterey

**Comment by Jasha10** [comment]
Hi @nils-werner!

Both interpolations (e.g. `"${foo}"`) and resolvers (e.g. `"${bar:baz}"`) are evaluated upon access. This means that interpolations and resolvers can depend on other parts of the config, and their values will not be stale when those other parts get updated. Let me demonstrate what I mean:

#### With resolvers:
```python
from omegaconf import OmegaConf
OmegaConf.register_new_resolver("get_size", lambda _parent_: len(_parent_)-1)
cfg = OmegaConf.create({"foo": "bar", "size": "${get_size:}"})
assert cfg.size == 1
cfg.baz = "qux"
assert cfg.size == 2  # the result of `${get_size:}` is still accurate!
```

#### With interpolations:
```python
from omegaconf import OmegaConf
cfg = OmegaConf.create({"foo": "bar", "baz": "${foo}"})
assert cfg.baz == "bar"
cfg.foo = "qux"
assert cfg.baz == "qux"  # the result of `${foo}` is still accurate!
```

The point is that OmegaConf objects (DictConfig and ListConfig) are highly-dynamic; the interpolations and resolvers allow for computation to be performed on the fly, updating based on any changes in the program state. (This is typically not as important in Hydra, which is downstream of OmegaConf).
As you mentioned, the `use_cache` flag is appropriate in cases where only one evaluation is desired.

I am closing this thread because this is more an OmegaConf question than a Hydra issue. Feel free to open another thread against the OmegaConf repository if you want to continue discussing.
