### ISSUE TITLE
[Bug] Key 'params' not in 'OptunaSweeperConf'

### ISSUE THREAD

**Issue by ai4prod** [facebookresearch/hydra#2046]
# 🐛 Bug
## Description

I'am trying to use optuna with hydra using OptunaSweeper conf. I have followed the example inside hydra repo at this link.

https://github.com/facebookresearch/hydra/tree/main/plugins/hydra_optuna_sweeper/example/

I have installed optuna and hydra integration following the documentation https://hydra.cc/docs/next/plugins/optuna_sweeper/

## Checklist
- [OK ] I checked on the latest version of Hydra
- [ NO ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **

python example/sphere.py hydra/sweeper=optuna --cfg hydra -p hydra.sweeper directly from hydra repository

** Stack trace/error message **

Key 'params' not in 'OptunaSweeperConf'
    full_key: hydra.sweeper.params
    object_type=OptunaSweeperConf

## Expected Behavior

Params will be in conf

## System information
- **Hydra Version** :  1.1.1
- **Python version** :  3.8
- **Virtual environment type and version** : Virtualenv 
- **Operating system** :  Linux

**Comment by Jasha10** [comment]
Hi @ai4prod,

The example you followed will only work with an unreleased version of Hydra.

> I have installed optuna and hydra integration following the documentation https://hydra.cc/docs/next/plugins/optuna_sweeper/

This link is pointing to the "Next" version of the documentation. For the current version of the docs, go to the top of that webpage and change the version from "Next" to "1.1".

Using the current version of the docs, the links to examples on github are changed to refer to `1.1_branch` instead of the latest commits from the `main` branch. Here is the relevant optuna example on github for Hydra v1.1: https://github.com/facebookresearch/hydra/tree/1.1_branch/plugins/hydra_optuna_sweeper/example

Of course, if you want to use the latest features, you can test out the development version of Hydra by installing directly from github!
```
pip install --upgrade git+https://github.com/facebookresearch/hydra.git@main
```

**Comment by ai4prod** [comment]
Hi @Jasha10 

ok thanks. I have not seen the "Next" on web page. Thanks for your help. I will try to update hydra with the latest version and try again.

**Comment by ai4prod** [comment]
Update Hydra solve the problem. Thanks
