### ISSUE TITLE
[Feature Request] Upgrade Ray Cluster Schema

### ISSUE THREAD

**Issue by piraka9011** [facebookresearch/hydra#2141]
# 🚀 Feature Request

The schema specified [here](https://github.com/facebookresearch/hydra/blob/1.1_branch/plugins/hydra_ray_launcher/hydra_plugins/hydra_ray_launcher/_config.py) for Ray Clusters is out of date.
This is the new schema: https://docs.ray.io/en/latest/cluster/config.html

## Motivation

Improve Ray Cluster plugin and keep it up to date

## Pitch

I'd like to update the schemas to reflect the new configs.
I want to make sure modifying the schema is the only thing I need to do and whether there are other dependencies I need to look out for.

**Are you willing to open a pull request?**
Yes

**Comment by jieru-hu** [comment]
hi @piraka9011 thanks for the issue. 
Feel free to update the schema. The CI should be able to catch any issue.  Other than that, pls also update the doc and add a [NEWS segment](https://hydra.cc/docs/development/overview/).

Do you happen to know since which version of Ray this was changed? What did you see when you try to run the launcher now?

**Comment by piraka9011** [comment]
The launcher works fine w/ Ray 1.3.0, but if I try to use any of the new keys in the YAML cluster config from Ray 1.3.0 or higher, I get an error from Hydra (OmegaConf) basically saying the key doesn't exist/match the schema (I'll try to get the exact error again.

**Comment by jieru-hu** [comment]
this is addressed in #2190 cc @piraka9011
