### ISSUE TITLE
[Feature Request] Config class generation for editor tab completion

### ISSUE THREAD

**Issue by tamuhey** [facebookresearch/hydra#216]
# 🚀 Feature Request

Generate subclass of `OmegaConf` so that get member of configuration with tab completion in editor.

```python
class Cfg:
    db = ""

@hydra.main()
def main(cfg: Cfg):
    cfg.d[TAB] # auto complete "db"
```

**Comment by omry** [comment]
Hi @tamuhey,
Thanks you for the feature request.
This is an interesting idea and it could be useful in some circumstances, however - due of the dynamic nature of the config in Hydra, in many cases this will not make sense.
Using an example from the tutorial:
`python my_app db=mysql `
and 
`python my_app db=postgresql`
Would create different config objects (with different fields).
The only way to know for sure what is in the config is to check it at runtime.

Something like this can be added as a plugin of Hydra, because I don't think this functionality belong with the code Hydra package.
If you want to give it a try I would be happy to advise on how to write such a plugin.
(Please start a discussion in the Google group).
I do not plan on implementing it as a part of the core of Hydra though, so I am closing this.
