### ISSUE TITLE
Hydra working directory

### ISSUE THREAD

**Issue by pietrolesci** [facebookresearch/hydra#2414]
After upgrading to hydra 1.2 if I call

```python
@hydra.main(version_base=None, config_path="conf", config_name="config")
def main(cfg):
    print(os.getcwd())
```
it prints the directory where the conf is rather than the usual `./outputs`

Context:
- Hydra config and `*.log` are still saved in the correct `./outputs` folder
- Any file I save from within the script is still relative to where the conf folder is located while before it was relative to the hydra output directory

Questions:
- Is this a new behaviour?
- Is there anything I can do to force hydra to the change the current directory for me?

**Comment by rsokl** [comment]
This is a documented change in 1.2: https://hydra.cc/docs/upgrades/1.1_to_1.2/changes_to_job_working_dir/ :

Hydra 1.2 introduces `hydra.job.chdir`. This config allows users to specify whether Hydra should change the runtime working directory to the job's output directory. `hydra.job.chdir` will default to False if version_base is set to >= "1.2" (or None), or otherwise will use the old behavior and default to True, with a warning being issued if hydra.job.chdir is not set.

If you want to keep the old Hydra behavior, please set `hydra.job.chdir=True` explicitly for your application.

For more information about `hydra.job.chdi`r, see [Output/Working directory](https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/#disable-changing-current-working-dir-to-jobs-output-dir) and [Job Configuration - hydra.job.chdir](https://hydra.cc/docs/configure_hydra/job/#hydrajobchdir).

**Comment by pietrolesci** [comment]
Hi @rsokl, thanks a lot for your answer! I completely missed the changelog but managed to solve the problem by specifying it manually. Thanks for your time!
