### ISSUE TITLE
[Feature Request] Allow "range" keyword from command line

### ISSUE THREAD

**Issue by stevenwalton** [facebookresearch/hydra#2464]
# 🚀 Feature Request

One of the reasons I switched to hydra is the ability to use arrays and 2D arrays. But sometimes I want to specify a range of numbers instead of just a list (e.g. I want to run inference on a set of seed values). The issue here is that from the configs I can use the "range" keyword and the parse this in my code to actually produce this range

```python3
def extract_range(args):
   start = 0
   step_size = 1
   start_end = args.inference.seeds.split("range(")[1].split(")")[0]
   if "," in start_end:
      nums = start_end.split(',')
      match len(nums):
         case 1:
            end = nums[0]
         case 2:
            start = nums[0]
            end = nums[1]
         case 3:
            start = nums[0]
            end = nums[1]
            step_size = nums[2]
         case _:
            raise ValueError
   args.inference.seeds = list(range(int(start), int(end), int(step_size))
```
This accurately allows me to specify a range from my config file. The problem here is that if I try to do this from the command line (`python main.py inference.seeds=range(0,100)`) I get an error about requiring `--multirun`. Using a list or string of values isn't a great alternative either because I might want to be producing hundreds of numbers. It also appears that ANY word used here causes a similar problem (`python main.py inference.seeds=r(0,100)` or `python main.py inference.seeds=rng(0,100)`) as it is always expecting a function. I seem to not be able to provide a string literal either with quotes. I can of course hack around this issue by doing ``python main.py inference.seeds=[`seq -s, 0 1 10`]`` but I think this is reasonably frustrating. 

It would be nice if there was consistency between notation within the config files and the command line interface.

**Comment by Jasha10** [comment]
Hi @stevenwalton,
Per [Hydra's Override Grammar](https://hydra.cc/docs/1.2/advanced/override_grammar/basic/#grammar), the override syntax `inference.seed=range(0,100)` is interpreted as a call to a sweep function (see the docs on [Extended Override syntax](https://hydra.cc/docs/1.2/advanced/override_grammar/extended/) for examples of what this means). This is why you're getting the error about requiring `--multirun`; sweep function invocations only work in multirun mode.

If I understand your use-case correctly, you want Hydra to parse the override `inference.seed=range(0,100)` as setting a string `"range(0,100)"` at the package `inference.seed`, rather than as invoking a sweep function. To achieve this, you should use quotes to make sure that Hydra interprets the override as you intended.

Please give the following a try:
```sh
python main.py 'inference.seeds="range(0,100)"'
```

See the docs on [quoted values](https://hydra.cc/docs/1.2/advanced/override_grammar/basic/#quoted-values) for more discussion on this topic.

**Comment by stevenwalton** [comment]
Hey @Jasha10,

Thanks for the quick follow-up. `python main.py 'inference.seeds="range(0,100)"'` works! I missed this in the override grammar, my bad.

**Comment by LukeLIN-web** [comment]
> 
I used 
`'model.params.Reddit.micro_pergpu="range(1,3)"' `
But failed.
`    if batch_size < num_micro_batch:
TypeError: '<' not supported between instances of 'int' and 'str' `

**Comment by LukeLIN-web** [comment]
> Hi @stevenwalton,
> 
> Please give the following a try:
> 
> ```shell
> python main.py 'inference.seeds="range(0,100)"'
> ```
> 
> If I understand your use-case correctly, you want Hydra to parse the override `inference.seed=range(0,100)` as setting a string `"range(0,100)"` at the package `inference.seed`, rather than as invoking a sweep function. To achieve this, you should use quotes to make sure that Hydra interprets the override as you intended.
> 
> See the docs on [quoted values](https://hydra.cc/docs/1.2/advanced/override_grammar/basic/#quoted-values) for more discussion on this topic.
> 
> Per [Hydra's Override Grammar](https://hydra.cc/docs/1.2/advanced/override_grammar/basic/#grammar), the override syntax `inference.seed=range(0,100)` (without quotes) is interpreted as a call to a sweep function (see the docs on [Extended Override syntax](https://hydra.cc/docs/1.2/advanced/override_grammar/extended/) for info on what this means). This is why you're getting the error about requiring `--multirun`; sweep function invocations only work in multirun mode.

Thank you , I tried `python mi.py -m model.params.Reddit.micro_pergpu="range(1,3)"` It works.

**Comment by omry** [comment]
Quoting the inner range here should not be needed in my opinion.
Try:
```
$ python main.py 'inference.seeds=range(0,100)'
```
