### ISSUE TITLE
how to get hydra.runtime.cwd

### ISSUE THREAD

**Issue by yuwl798180** [facebookresearch/hydra#250]
i want to know how to get runtime.cwd in code?

for the purpose:

when i import the function that not in the root, and pass the cfg in it. then i can't correctly use the file_path because the `os.getcwd()` not in the root, it changes to the `hydra.run.dir`

the code just like that:

```python
from utils import load_data

@hydra.main(config_path='conf/config.yaml')
def main(cfg):
    data = load_data(cfg.data_path)
```

the directory like that:

```
utils
-- __init__.py
-- ioUtils.py  ( load_data func in this)

mian.py
```

so i want to get `hydra.runtime.cwd`, and pass args like `os.path.join(cwd, data_path)`

or can i have other elegent way coding?

**Comment by omry** [comment]
I am landing a change soon that will provide those APIs.
See #252 
Once this lands, you can install hydra from master to get this functionality before I release a new version.

Alternatively you can copy this to your own code, but I suggest you don't because it's using internal APIs that I may change in the future.
