### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by tchaton** [facebookresearch/hydra#265]
# 🚀 Feature Request

Hey there,

I would be great to merge advantages from argparse and hydra.

Hydra: Tree based parsing
Argparse: Simple argument description.

I was thinking it could be possible to provide arguments to a script by providing only the leaf as arguments (or the unique smallest id to find it in the tree.)

Example based on yours:
db.mangodb.something
db.sql.something

python my_script.py db.mangodb.something="something" could become python my_script mangodb.something="something"

df.sql.something didn't exist, it could become directly python my_script.py something="something"
and the argument something could be found within args.db.mangodb.something.

## Motivation

**Is your feature request related to a problem? Please describe.**

I think it could make argument inputs as readable as argparse, but the flexibility provided by tree based arguments.

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))

**Comment by omry** [comment]
Hi @tchaton,
Thanks for your interest in Hydra and for the interesting idea.
This would present some challenges:
Got example, there is an inherent ambiguity here:
```yaml
foo:
   bar: 10

baz:
  foo:
     bar: 10
```
In this case, what would you expect
`python foo.py foo.bar=20` resolve to?

Additionally, the command line space is already overloaded:
with the same syntax, you cam override defaults `db=mysql` (if a config group called `db` exists) or override a variable db to mysql if such a config group does not exist.

Adding more ambiguity might be pushing it too hard.
another problem that as you evolve your config, previously unambiguous command line overrides might become ambiguous - resulting in previous commands becoming invalid.

At this point I have no plans of implementing this behavior. it might be worth considering it as an experimental optional behavior - but because it effects how the configuration is loaded it can not be defined in the configuration.
something like this might be implemented as plugin in the future (the plugin hook is not available for it right now), or as a new syntax like `python foo.py ~mysql.hostname=localhost`. 

If you would like to try exploring adding support for this I am willing to evaluate a PR, but as I would be leaning toward rejecting it as it might cause more harm than good overall.
I am closing this for now, bug feel free to continue discussing this here (or in the google group).
