### ISSUE TITLE
[Bug] Documentation inconsistency for `utils.get_original_cwd`

### ISSUE THREAD

**Issue by dhpollack** [facebookresearch/hydra#278]
# 🐛 Bug

The tutorial for working directories has a few commands for setting the working directory [see here](https://cli.dev/docs/tutorial/working_directory), but the version of hydra on pip does not have these functions.  Additionally, the install instructions do not include instructions on how to install from source (even if that's fairly trivial).  The simple solution is to update the wheels on pip.  Another alternative would be to put on the installation page that hydra is rapidly developing and suggest that one can install from source directly.

## System information
- 0.10.0 from pip
- python 3.7
- arch linux

## One more thing...
This is very minor but the pip version is `0.10.0` and the github master version is also `0.10.0`, but they not the same as evidenced by this issue.  You should probably bump the version of git master.  Keep up the good work, I think this is a great idea.

**Comment by omry** [comment]
Hi David, thanks!
I am aware of this, unfortunately the documentation system I am using (Docusaurus 2) does not yet support multiple documentation versions, and since I like to update the docs as I write new features it results in this inconsistency.

I had quiet a bit of travel this month, so the release of the next version is delayed, you can follow the progress toward 0.11.0 [here](https://github.com/facebookresearch/hydra/milestone/3).

The instructions for installing from source are in the Development/Contributing [section](https://cli.dev/docs/development/contributing) of the docs.

I agree with you that this is not great.
One thing I might do is to make a pre-release (0.11.0-rc*) that will be considered unstable until I 0.11.0 is released).

**Comment by dhpollack** [comment]
I think the changing the master to an -rc is a really good idea. It'd give the user a hint that something has changed.
