### ISSUE TITLE
[Question] How can I retrieve the configuration dictionary without using the cli?

### ISSUE THREAD

**Issue by brn7rng** [facebookresearch/hydra#2795]
I want to retrieve the whole dictionary without using the hydra.main decorator. I have a nested folder structure:

|-- experiment
|   |-- exp1.yaml
|   |-- exp2.yaml
|-- bar
|   |-- default.yaml
|-- foo
|   |-- default.yaml

Where exp1 looks like this:

defaults:
 - experiment
 - bar: default
 - foo: default

Usually I will interact with the cli by the following command:
python script.py --config-dir experiment --config-name exp1

In some cases I want to retrieve the whole dictionnary though, without using the cli and the decorator. Is there a way to do this?

Thank you

**Comment by odelalleau** [comment]
You can use the [Compose API](https://hydra.cc/docs/advanced/compose_api/)

**Comment by brn7rng** [comment]
Thank you for the quick answer. In my case compose does not seem to work, it does not resolve the parameters correctly. I added one parameter to each yaml (and added a dataclass to validate against):

foo/default.yaml:
```
parameter1: 1
````

bar/default.yaml:
```
parameter2: 2
```

I get the following result:
```
bar:
  parameter1: ???
foo:
  parameter2: ???
```

My script.py looks like this:
```
initialize(version_base=None, config_path="config/experiment", job_name="test_app")
cfg = compose(config_name="exp1", overrides=["bar=default", "foo=default"])
print(OmegaConf.to_yaml(cfg))
```

**Comment by odelalleau** [comment]
What's your `exp1.yaml`?

**Comment by brn7rng** [comment]
```
defaults:
  - experiment
  - foo: default
  - bar: default
```

**Comment by odelalleau** [comment]
Hmm, works for me.

```
.
├── config
│   └── experiment
│       ├── bar
│       │   └── default.yaml
│       ├── exp1.yaml
│       ├── experiment.yaml
│       └── foo
│           └── default.yaml
└── my_app.py
```

```python
 py py39-hydra  tmp !6 ?14  ~/s/hydra/examples/tutorials/basic/your_first_hydra_app/2795  v config/experiment/foo/default.yaml                                                                         ok  2.42 cpu
from hydra import compose, initialize
from omegaconf import OmegaConf

initialize(version_base=None, config_path="config/experiment", job_name="test_app")
cfg = compose(config_name="exp1", overrides=["bar=default", "foo=default"])
print(OmegaConf.to_yaml(cfg))
```

Output:
```
foo:
  parameter1: 1
bar:
  parameter2: 2
```

**Comment by brn7rng** [comment]
If I use the folder structure that you provided it also works for me. My folder structure is a bit different (see first comment), the `experiment` folder is at the same height as the `bar` and `foo`.

In theory I could change the code to your folder structure but the `experiment` folder contains a lot of files and that would be very messy. Is there a way to make it work as above?

**Comment by odelalleau** [comment]
> If I use the folder structure that you provided it also works for me. My folder structure is a bit different (see first comment), the `experiment` folder is at the same height as the `bar` and `foo`.

Oh, sorry I missed that. But that doesn't really make sense -- I don't undersand how you didn't get an error, or how you are able to get a working config with `@hydra.main()`. You'd need to provide a full self-contained example where `@hydra.main()` works so I can suggest a specific approach.

But roughly speaking here are the things you can tweak to make it work:
* The `config_path` you pass to `initialize()`. Since it's the root config folder, normally you can only access configs that are within it. Which means that with your folder structure, when you use `config_path="config/experiment"`, you can't actually access the configs under `foo` or `bar`...
* ... unless you modify the [Config search path](https://hydra.cc/docs/advanced/search_path/)
* Another (potentially cleaner) approach is to use `config_path=config` then import `experiment: exp` from a base config under the `config` folder.
* To access configs in the defaults list that are not under the current folder, you can use an absolute path, e.g. in `exp1.yaml` you may need to use
```yaml
defaults:
  - experiment
  - /foo: default
  - /bar: default
```

**Comment by brn7rng** [comment]
No problem, thanks for the quick answer. I am using a dataclass calles ExperimentConfig to validate the main hydra config. My script looks the following:

```
@hydra.main(
    version_base=None,
    config_path="config",
)
def main(dict_cfg):
    cfg: ExperimentConfig = OmegaConf.to_object(dict_cfg)
    print(cfg)
```

And I run the following command:
```
python path/to/script.py --config-dir config/experiment --config-name exp1
```

**Comment by odelalleau** [comment]
So I guess you're also using the ConfigStore? If you still need help then please provide a full minimal repro example.

**Comment by brn7rng** [comment]
Hello Olivier, thanks for your help. I decided to switch to your recommended directory structure, as it is the intended way. Now it works as intended!
