### ISSUE TITLE
[Feature Request] Enhance Hydra with Support for Global Custom Resolvers in DVC Integration

### ISSUE THREAD

**Issue by lefos99** [facebookresearch/hydra#2835]
# 🚀 Feature Request

## Motivation

**Is your feature request related to a problem? Please describe.**
When integrating Hydra with [DVC](https://github.com/iterative/dvc), there's a lack of support for global custom resolvers. 

## Pitch

**Describe the solution you'd like**
I propose that Hydra should include support for global custom resolvers that [DVC](https://github.com/iterative/dvc) can recognize and use out of the box. This enhancement would allow users to register custom Omegaconf resolvers, which then DVC can _understand_ and use when converting the `conf/config.yaml` to its [`params.yaml`](https://dvc.org/doc/command-reference/params#params), which is generated during a [DVC experiment](https://dvc.org/doc/user-guide/experiment-management/hydra-composition#setting-up-hydra). 

**Describe alternatives you've considered**
A workaround would involve preprocessing configuration files before they're consumed by DVC, but this is less efficient and defeats the purpose of using Hydra for its powerful configuration management capabilities.

**Are you willing to open a pull request?**
I am not able to open a pull request at this time, but I am eager to assist by discussing and providing use cases or examples to support the development of this feature.

## Additional context
For reference, you can see the specific [issue](https://github.com/iterative/dvc/issues/9731#issuecomment-1873877722) in DVC's repo. This feature would not only benefit my use case but also enhance the experience for other users facing similar challenges in dynamic configuration management within their data pipelines.

**Comment by dberenbaum** [comment]
Hi, coming here from DVC, I want to stress that this is less about DVC integration and more about having generic support for global custom resolvers that are defined as part of configuration instead of inside the user script. Users have been asking for this in DVC, but it seems a better fit inside Hydra. Not sure if we can prioritize helping to implement it, but wanted to get thoughts on whether there is interest in supporting it and how first.

**Comment by odelalleau** [comment]
It is unlikely that Hydra / OmegaConf will ever support user-provided resolvers defined in the config by default, as it would make any Hydra-based app vulnerable to code injection through the config.

The DVC issue seems to have more details but I don't have time to fully understand it right now. It may be helpful if you could describe how Hydra could solve the (generic, not DVC-specific) problem without the vulnerability concern I mentioned.

**Comment by dberenbaum** [comment]
It might be helpful to look at https://github.com/iterative/dvc/issues/9731#issuecomment-1884836167 or have @lefos99 explain how they already do this within `hydra_plugins`. I suggested opening an issue here because it doesn't look to me like this is intended behavior.

**Comment by lefos99** [comment]
Hey @odelalleau,
Thanks for your reply already. :slightly_smiling_face: 

As @dberenbaum already metnioned, we use the hydra plugins in the following way:
We're leveraging [Hydra's plugins system](https://hydra.cc/docs/0.11/advanced/plugins/). This allows us to define our custom resolvers just once in a dedicated file within our project, typically at `git_project/hydra_plugin/resolvers.py`. Here's a glimpse of how it's set up:

```python
# git_project/hydra_plugin/resolvers.py

from omegaconf import OmegaConf

def plus_10(x: int) -> int:
  return x + 10

OmegaConf.register_new_resolver('plus_10', plus_10)
```

```python
# another script that uses hydra
# I do not need to define any resolver here
from omegaconf import DictConfig
import hydra

@hydra.main(version_base=None, config_path='conf', config_name='config')
def main(cfg: DictConfig) -> None:
    print(cfg)
```
By doing this, we avoid having to register resolvers in each individual script, keeping our codebase clean and dry.
The problem is that this defined custom resolver (`plus_10`) is visible to my python scripts, but it is not _visible_ to pip packages. (e.g. DVC) 

> it doesn't look to me like this is intended behavior.

I think that according to [this](https://hydra.cc/docs/advanced/plugins/develop/#automatic-plugin-discovery-process), it is, no?

**Comment by odelalleau** [comment]
Thanks for clarifying!

> The problem is that this defined custom resolver (`plus_10`) is visible to my python scripts, but it is not _visible_ to pip packages. (e.g. DVC)

Is DVC using `hydra.main()`? If yes I'm surprised that it wouldn't work, and if not then how does DVC interact with Hydra?

**Comment by dberenbaum** [comment]
> Is DVC using `hydra.main()`? If yes I'm surprised that it wouldn't work, and if not then how does DVC interact with Hydra?

No, see [here](https://github.com/iterative/dvc/blob/d711ecda04debf61127f31bc46f88ddfd861d786/dvc/utils/hydra.py#L16) for how it initializes Hydra. We could look into whether DVC can initialize Hydra in such a way that these custom resolvers work, but again I'd like to clarify if this is expected behavior for Hydra. The way it is being used above for global custom resolvers is not inside any submodule and does not implement a Plugin class. This indicates that Hydra is executing all code placed inside `hydra_plugins`, which I think would lead to the same types of code injection concerns you raised initially.

**Comment by odelalleau** [comment]
I see, thanks, so DVC is using the Compose API.

Would you be able to do a quick test to see if calling `Plugins.instance()` first would "magically" make your plugin be loaded and the resolver available? (requires `from hydra.core.plugins import Plugins`). If yes it means the issue is that plugins aren't loaded when using the Compose API, which may be intended (the plugins offer functionalities that are not relevant for the Compose API) but could potentially be changed (possibly with a new flag). If this doesn't work then it means your plugins aren't discoverable anymore when running with DVC which could be related to Python paths.

Code injection through `hydra_plugins` is ok, this already exists and someone with enough permissions to do it can probably already execute arbitrary code anyway, so let's not worry about it.

**Comment by dberenbaum** [comment]
Thanks @odelalleau! I wanted to make sure this would continue to be supported before I took this any further in DVC. 

I can see that it is indeed related to Python paths, which we can handle in DVC. I think we can close this issue on the Hydra side.

**Comment by odelalleau** [comment]
> I can see that it is indeed related to Python paths, which we can handle in DVC. I think we can close this issue on the Hydra side.

Just to confirm before closing this issue, I have verified that plugins are indeed loaded when using the Compose API (I tested with `initialize()` and `initialize_config_dir()`. As a result, it should be possible to make it work by ensuring that your custom `hydra_plugins` folder is in `PYTHONPATH`.

Please feel free to reopen this issue if this solution does not work for you.
