### ISSUE TITLE
[Feature Request] Use JSON as an alternative to YAML

### ISSUE THREAD

**Issue by faroit** [facebookresearch/hydra#408]
# 🚀 Feature Request

hydra seem to only support YAML files for configurations. For various reasons, many people prefer other formats such as JSON. 

## Motivation

YAML and JSON are very similar and support for most data types are present in both. This allows to implement a JSON parser that supports the same features as the YAML version. Furthermore JSON parsers in Python are typically faster than YAML.

**Comment by omry** [comment]
Hi, thanks for the feature request.
YAML is compatible which JSON: valid JSON is (almost always) valid YAML.
this means you can put json strings inside YAML files and they will be parsed properly.

When composing configurations with your defaults:
```yaml
defaults:
  foo: bar
```

Hydra will look for foo/bar.yaml in your config search path. this means adding additional extensions would involve checking for all supported extensions in some order. I don't think this is worth the overhead and the extra complexity at this point.

I know existing systems may be using JSON. In my opinion YAML is a better format for configuration and I would like to keep it as the primary supported one.

Hydra 1.0.0 will add configuration source abstraction which can come handy here to add opt-in support for json files.
I will keep this open for now to look into that possibility later, but in general I am not thrilled about adding json support to hydra-core.

**Comment by faroit** [comment]
> Hydra 1.0.0 will add configuration source abstraction which can come handy here to add opt-in support for json files.
I will keep this open for now to look into that possibility later, but in general I am not thrilled about adding json support to hydra-core.

sounds good to me.

**Comment by omry** [comment]
Thinking about it some more config source may be inappropriate (it adds support for additional locations for configs, not for additional types - which are orthogonal).
the rest stands. I will consider this but it's not very likely.

**Comment by festeh** [comment]
There's also a Jsonnet language, which is compared to YAML [here](https://jsonnet.org/articles/comparisons.html). For example, it's used in [AllenNLP](https://allennlp.org/) library. Would it be possible to let user write custom data loading functions in configuration source abstraction in order to support such files?

**Comment by omry** [comment]
Thanks for the pointer to Jsonnet.
There are a few things here:

1. OmegaConf is a data model than a language parser. it does add runtime features like interpolations and resolvers (and obviously merging of objects).
It is somewhat agnostic to the underlying format, but at the moment there is built in support for YAML and dataclasses. (new in OmegaConf 2.0.0, not yet in Hydra).
I am planning to add support for simple expressions to OmegaConf [here](https://github.com/omry/omegaconf/issues/91). Such support would not work properly with Jsonnnet interpolation support means this has to happen at runtime.

2. Hydra got some magical behavior that are making it hard, I described those in the comment above. (defaults list not containing the file extension and what the implications are).

3. Frameworks alike AllenNLP will have to be adapted to use Hydra to benefit from it. some of those changes involves potentially using a different configuration language. but there could be other deeper changes.

I am keeping this feature request option to potentially implement support for other config formats in the future (user provided or not, this is challenging).
As I said this is a low priority.

**Comment by faroit** [comment]
> I know existing systems may be using JSON. In my opinion YAML is a better format for configuration and I would like to keep it as the primary supported one.

YAML may indeed be a better format for a human readable config format. However, I believe that the fact that it cannot be easily parsed and validated in python without installing additional dependencies (also true for other languages), makes it significantly harder to use in real world.

**Comment by omry** [comment]
@faroit, This is a very weak justification in the context of Hydra.
If you want to use Hydra, you you can use it with YAML.
Hydra is a MUCH bigger dependency to add than pyyaml. by using Hydra you buy into accepting it's dependencies.

**Comment by faroit** [comment]
I don't understand why Hydra would be heavy on dependencies. I only see OmegaConf which in itself only depends on PyYAML - hence with json, Hydra could be almost pure python.

It seems that json support is not seen as a viable option for this project so I'm closing this.

**Comment by omry** [comment]
@faroit I am not referring to the request but to the argument that yaml as a dependency is a problem for Hydra:
pyyaml is a hard dependency for OmegaConf, OmegaConf is a hard dependency for Hydra.

if you want to use Hydra, you will have a pyyaml dependency even this is implemented and there is native support for json files.
I see no reason to work toward eliminating this dependency.

The reason I commented here is that I saw your last comment which I missed before when I went through all the existing tasks.
Allow me to be the one closing issues. Refer to my [earlier comment](https://github.com/facebookresearch/hydra/issues/408#issuecomment-585830324) for reasoning as to why this is still open.

**Comment by omry** [comment]
Thanks file filing the request.

Hydra is using a logical name for configs, which does not include a file extension.
Configs can be yaml files on the file system or in Python modules, and objects in the ConfigStore.
ConfigSources can add additional locations for configs which have their own naming rules.

All this makes it difficult to support json files without introducing some fixed cost for checking both yaml and json in any config access.

Since this feature was open, it generated little interest from the community and overall I do not think it's worth adding additional complexity to Hydra to support it.

Closing.

**Comment by teocasse** [comment]
We are using hydra for our projects and we are happy with its feature set, so kudos for the great work!

From our point of view, a possible enhancement would be adding support for other configuration formats (e.g. .toml, .hocon). We are already using .toml for other purposes (integration with build systems) and it would offer a nice opportunity for consolidation.

I read through the motivations against introducing support for JSON (as well as the other thread https://github.com/facebookresearch/hydra/issues/1050), and IMHO it seems that the biggest issue (the framework implicitly assuming a .yaml extension when looking for config files) could be vastly mitigated if the user would be required to specify the config format when initializing Hydra (by passing it as a parameter): if no format is provided we continue using yaml, but if a different format is provided (e.g. "toml"), then internally Hydra changes its behavior to look for .toml files instead of .yaml files and do the parsing accordingly. Clearly, this prevents the users from mixing different config formats (which would be a bad user choice anyway).

I decided to add this comment since it seemed to me that the biggest cons were related to supporting both yaml and another format/extension _ simultaneously in the same application_, and I do not think this is necessary. Has some consideration been made into allowing to define the config format at application level?

**Comment by omry** [comment]
Hydra itself has yaml config files, and so does Hydra plugins.
When using Hydra - different frameworks / systems can contribute config files at the same time. So all supported input config types has be be supported simultaneously (in the same app).

**Comment by teocasse** [comment]
Apologize for the late reply... It is definitely a valid concern. Thinking about it though, I realized that additional frameworks that contribute config files (including Hydra) do so by appending their path to the search path. So, instead of making the format homogeneous at application level, one possibility could be to make the file format a property of a search path entry and making it homogeneous at search path entry level, i.e.:
* each path added to the search path can optionally define the file format _associated to that path_ (with the default being yaml if nothing is specified)
* within that path, only that file format/extension is supported, other formats will not be read/accessed.
That way, the user could choose the preferred format/extension for their application, while dependencies that use hydra to contribute their configuration do not need to provide their config files in X different formats, as they specify the format of _their_ configuration.

This is simply a suggestion of course, it's up to Hydra contributors to define the roadmap. But IMHO, it would be good for the framework to not be coupled to a specific config format or extension.

**Comment by elgehelge** [comment]
What I find extremely valuable in regards to TOML and JSON is the type support. Currently with Hydra I would have to define my schema in the code using `dataclasses`, then make sure to register it using `ConfigStore.instance(name="config_schema", node=MyConfig).store`, and then I can typecheck my config files by adding 
```
defaults:
  - config_schema
``` 
to the beginning of the config files.

If TOML or JSON was supported then I could imagine having my types defined directly as a configuration file in a way that would not require me to write dataclasses for every API entrypoint.
