### ISSUE TITLE
[Feature Request] Emulate conventional commandline args

### ISSUE THREAD

**Issue by r0f1** [facebookresearch/hydra#446]
Hi, this is not a feature request and more a general usage question. I'd you really like to give hydra a try in one of my existing projects. I have a program that from the outside looks like this to the user:

```
python main.py --arg1="ABC" --arg2="DEF" 
```

I know that you can create required arguments using `???` (like described [here](https://github.com/facebookresearch/hydra/issues/215#issuecomment-540210974) ). A program using hydra would look like this: 

```
python main.py arg1="ABC" arg2="DEF" 
```

Is it somehow possible to add the `--` (minus minus)? This may not sound like a big deal, but it is somewhat of a big deal to me, because it not, I would have to change several interface, when I use hydra.

Thank you, Flo

**Comment by omry** [comment]
hi @r0f1, can you join the chat?

**Comment by omry** [comment]
Hi @r0f1,
Thanks for the suggestion.

Hydra is using conventional command line arguments for several basic things that are common to all Hydra apps, like --help, --run, --multirun and more.

Basically, Hydra offers a much more flexible and powerful command line interface than traditional command line interfaces, but it is also incompatible with them.
one problem is that --flag is not supported by Hydra, every command line override must be in the the form of key=value.
Another problem is that I do not want to have a conflict with the Hydra command line flags I mentioned above.

If you switch to Hydra, you will probably end up introducing a lot of new command line overrides that does not exist in your current system. this means that you will need to change your calling code anyway.
Trying to maintain compatibility to your existing command line interface may seem like a good idea, but in the long run it will cost you more time than just accepting that things should change.

If you really must do this, you can wrap Hydra with your own command line interface, and transform sys.argv into something Hydra can accept before you call the hydra.main() function.

Feel free to continue discussing here or in the chat, but I do not intend to support this in Hydra.

**Comment by r0f1** [comment]
Thanks for the elaborate response!

**Comment by jpmartineau** [comment]
This is quite frustrating.

**Comment by omry** [comment]
Feel free to use use OmegaConf directly or use the Hydra's Compose API, both of which will allow you to manage the command line however you like.

**Comment by hannw** [comment]
I have a use case for this request. I am running `fairseq-hydra-train` with `torch.distributed.launch` which automatically passes a `--local_rank` flag to hydra and this throws 
```
fairseq-hydra-train: error: unrecognized arguments: --local_rank=1
```
error. If hydra couldn't support adding additional command line args out of the box, users will need to jump through lots of unnecessary hoops to circumvent this error.

**Comment by omry** [comment]
Supporting standard command line flags for Hydra application will not be supported. Refer to my detailed comment above to understand the reasoning.

This will have to be resolved at a different layer (maybe by passing the rank as an environment variable instead of a command line flag).

**Comment by jpmartineau** [comment]
hannw:

You need to write a arg-preprocessing function that remaps your "--args val" or "--args=val" parameters to "cfg.something.arg=val". This can be done by accessing and rewriting sys.argv before calling main. If you need the mapping to be dynamic (I did), you can pass it as an argument to the function itself.

Since many real-life scenarios (e.g.: AzureML HyperDrive) require this, such a utility function should be included with hydra, but sadly isn't, and probably won't ever be from what I read. As I wrote earlier, it's quite frustrating and time-consuming for everyone

I included some code here. This should help those who are stuck with legacy code, or third-party calling sites.

Disclaimer: It's a stripped-down version of my code, and I haven't tested this stripped down version, but the code it's based on works well, so it should be somewhat ok.

[hydra_argv_remapper.zip](https://github.com/facebookresearch/hydra/files/6826378/hydra_argv_remapper.zip)

**Comment by hannw** [comment]
@omry I understand the design principle. It's just that if the principle is followed religiously it would be unnecessarily inconvenient for users. In the case I mentioned, the flag was enforced by `torch.distributed.launch` and there are many real world cases as @jpmartineau mentioned.

Thank you @jpmartineau for providing the code example. I created a wrapper on top of `fairseq-hydra-train` similar to your suggestion to remap the args and was able to make distributed training working. If adding additional args or at least "ignoring" unrecognized args are supported in hydra, it would make the adaptation with other packages much easier.

**Comment by jpmartineau** [comment]
@hannw You're welcome. In my real code, I actually pass the argument mapping as an argument. I create the argumeent mapping on the calling site. I dump it to json and I base64 encode it. I pass it as an argument --arg_map which is intercepted in my function. It checks if an --arg_map argument exists. If it's present, I then proceed to deserialize it and perform the mapping. That allows me more flexibility, since I don't always know in advance which arguments I need to process. Cheers!
