### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by umvarma** [facebookresearch/hydra#699]
# 🚀 Feature Request

Accessing the application help and making use of it from the application code

## Motivation

**Allow the application to access the application help and make use of (ex: print/show it to the user) when incorrect usage is identified.**

## Pitch

Identify wrong usage patterns and showing the correct usage to the user is a critical aspect in any application. Hydra may be enhanced in future to specify mandatory configuration parameters and constraints specifying correct usage patterns. But, it is also a good idea to allow the application access the application help text and make use of it when it encounters wrong usage scenarios.

If I understand correctly, Hydra doesn't provide any mechanism to the application to access the help text/template provided in the hydra configuration.  Please correct me if I am wrong. My exposure to hydra is just about a day old. The methods with access to the application seemed to be in the internal methods of Hydra. It would be of great help if Hydra provides a way to expose the help text to the application some way or other.

Please correct me, if such a mechanism already exists.

**Describe the solution you'd like**
Provide a method such as hydra.app_help() or hydra.utils.app_help()

**Comment by omry** [comment]
Hi @umvarma!
Hydra 1.0 has improved error messages that are already pretty helpful. I have some additional ideas about improving the error messages like [this](https://github.com/omry/omegaconf/issues/265) one.

My concern is that the application help can be very large for complex applications and it will overwhelming for the user to get so much information instead of a targeted message relevant to their actual mistake.

Please try Hydra 1.0, the error messages are significantly better than Hydra 0.11.

If this is not enough, can describe a concrete scenario when the user make some kind of usage mistake and the generic help is more helpful than the specific error message in Hydra 1.0?

**Comment by umvarma** [comment]
> Hi @umvarma!
> Hydra 1.0 has improved error messages that are already pretty helpful. I have some additional ideas about improving the error messages like [this](https://github.com/omry/omegaconf/issues/265) one.
> 

Thank you. The version I am using 0.11. I will check the 1.0 and update on this.

**Comment by omry** [comment]
I am closing this, please reopen if you still want to make the case for it after you try Structured Configs.
