### ISSUE TITLE
Sweeping over lists and avoiding sweeping when quoted

### ISSUE THREAD

**Issue by amolchanov86** [facebookresearch/hydra#96]
Should sweep over `list` as 2 list values: 
`python run_hydra.py -m list=[1,2],[a,b]`

Should sweep over `str` as 2 string values: 
`python run_hydra.py -m str="[1,2]","[a,b]"`

Should not sweep `fakelist` but sweep over `anotherpar` instead
`python run_hydra.py -m fakelist="[1,2],[a,b]" anotherpar=a,b`

**Comment by Blitzman** [comment]
Up!

**Comment by omry** [comment]
@Blitzman, this is pretty low priority.
I suggest that for now you put your lists in config files and sweep on those.
if this is not viable, try using a different list separator.

**Comment by Blitzman** [comment]
Thanks @omry, what do you mean by a different list separator?

**Comment by omry** [comment]
Change your code to use another separator. instead of splitting on "," split on something else.
```
"foo=a b c"
cfg.foo.split(" ")
```
Or maybe `foo=a.b.c`, or `"foo=a|b|c"`.
Most good separator chars are already taken by the shall, so you may want to quote the string as in my examples.

Feel free to join the chat if you want a followup discussion.

**Comment by omry** [comment]
#573 will offer a solution here, feel free to send a PR for it.
